name: "Github Actions Plugin Tester"
author: "Webtech Network"
description: "A super cool sandbox environment for testing how github actions works with custom plugins."
inputs:
  html-weight:
    description: "Weight for the HTML grading section."
    required: true
    default: "30"
  css-weight:
    description: "Weight for the CSS grading section."
    required: true
    default: "40"
  js-weight:
    description: "Weight for the JavaScript grading section."
    required: true
    default: "30"
  timeout:
    description: "Duration (in minutes) before the grading process is terminated. Defaults to 10 minutes."
    required: false
    default: "10"
  token:
    description: >
      GitHub token used to check repository content and provide feedback. By default, 
      this uses the repository token provided by GitHub Actions. You can customize this
      by replacing this token with a user token which has write-access to your repository. 
      Note that the token will be accessible to all repository collaborators.
    default: ${{ github.token }}

outputs:
  result:
    description: "Base64-encoded JSON containing the results of the grading."

runs:
  using: docker
  image: "Dockerfile"  # The Docker image containing the autograder
  args:
    - ${{ inputs.html-weight }}
    - ${{ inputs.css-weight }} 
    - ${{ inputs.js-weight }}
    - ${{ inputs.timeout }}
    - ${{ inputs.token }} 
